chore: upgrade docker environment

diff --git a/docker/nginx/Dockerfile b/docker/nginx/Dockerfile
--- a/docker/nginx/Dockerfile
+++ b/docker/nginx/Dockerfile
@@ -1,17 +1,12 @@
-FROM nginx:alpine
+FROM nginx:1.24-alpine3.17-slim
 
-LABEL maintainer='Iqbal Hikmat Prahara <iprahara@alphatree-capital.com>'
+LABEL maintainer='Iqbal Hikmat Prahara'
 
 COPY nginx.conf /etc/nginx/
 COPY app.conf.template /etc/nginx/templates/
 COPY docker-entrypoint.sh /
 
-RUN apk update \
-    && apk upgrade \
-    && apk --update add logrotate \
-    && apk add --no-cache bash
-
-RUN apk add --no-cache curl
+RUN apk add --no-cache --update logrotate curl bash
 
 RUN set -x ; \
     addgroup -g 82 -S www-data ; \
@@ -29,8 +24,13 @@ COPY logrotate/nginx /etc/logrotate.d/
 # Set upstream conf and remove the default conf
 RUN echo "upstream octane-server { server ${PHP_UPSTREAM_CONTAINER}:${PHP_UPSTREAM_PORT}; }" > /etc/nginx/conf.d/upstream.conf
 
+# Clean up
+RUN rm -rf /var/cache/apk/*
+
 ADD ./startup.sh /opt/startup.sh
 RUN sed -i 's/\r//g' /opt/startup.sh
 CMD ["/bin/bash", "/opt/startup.sh"]
 
 EXPOSE 80
+
+HEALTHCHECK --interval=5m --timeout=3s CMD curl --fail ${NGINX_HOST} || exit 1
